apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
spec:
  selector:
    matchLabels:
      web-service: statistics
  template:
    metadata:
      labels:
        web-service: statistics
        system: server
    spec:
      containers:
        - name: statistics-service
          image: 3176a6a/carrentalsystem-statistics:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "250m"
          env:
            - name: ApplicationSettings__Secret
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: security-token-secret
            - name: ApplicationSettings__SeedInitialData
              valueFrom:
                configMapKeyRef:
                  name: environment-settings
                  key: seed-initial-data
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: statistics-service-connection-string
            - name: ConnectionStrings__CronJobsConnection
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: statistics-service-cron-jobs-connection-string
          volumeMounts:
            - name: statistics-service-data
              mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
        - name: statistics-service-data
          persistentVolumeClaim:
            claimName: statistics-service-data
